program: src/ml_ops/train.py
name: sweepdemo
project: corrupt_mnist
entity: adlcv_memorization
method: bayes

metric:
  name: validation_loss
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1

  batch-size:
    values: [16, 32, 64]

  epochs:
    values: [5, 10, 15]

run_cap: 10
